---
- name: Add Postgres repo key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add Postgres repo
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main

- name: Install PostgreSQL
  apt:
    name:
      - "postgresql-{{ postgres_version }}"
      - "postgresql-client-{{ postgres_version }}"
      - "libpq-dev"
      - "python3-psycopg2"
    update_cache: yes

- name: Create postgres data dir
  file:
    path: "{{ postgres_datadir }}"
    state: directory
    mode: '0750'
    owner: postgres
    group: postgres

- name: Create conf.d
  file:
    path: "/etc/postgresql/{{ postgres_version }}/conf.d"
    state: directory
    owner: postgres
    group: postgres

- name: Create main
  file:
    path: "/etc/postgresql/{{ postgres_version }}/main"
    state: directory
    owner: postgres
    group: postgres


- name: Copy Postgres conf
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    owner: postgres
    mode: 0644
    force: yes
  notify: Restart Postgres

- name: Flush handlers
  meta: flush_handlers

- name: Init postgres datadir
  shell: "sudo -u postgres /usr/lib/postgresql/{{ postgres_version }}/bin/initdb -D {{ postgres_datadir }}"
  register: postgres_datadir_init
  ignore_errors: yes

- name: Start postgres in datadir
  shell: "sudo -u postgres /usr/lib/postgresql/{{ postgres_version }}/bin/pg_ctl start -D {{ postgres_datadir }}"
  register: postgres_datadir_start
  ignore_errors: yes

- name: Ensure Postgres service started
  systemd:
    name:  postgresql
    state: started

- name: Change Postgres default user password
  postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_pass }}"

- name: Check simple SQL
  shell: ' sudo -u postgres psql -c "select 1+1"'
  register: sql_output
  ignore_errors: yes

- name: Sql output
  debug:
    msg: "{{ sql_output.stdout }}"
  ignore_errors: yes