---
- name: Install default packages Debian
  apt:
    name:
     - iotop
     - htop
     - mc
     - net-tools
    update_cache: yes
    autoremove: yes
  when: ansible_os_family == 'Debian'

- name: Install default packages Redhat
  yum:
    name:
     - iotop
     - htop
     - mc
     - net-tools
    update_cache: yes
  when: ansible_os_family == 'Redhat'
