FROM {{ docker_image }}

ADD ./{{ nginx_index }} /var/www/html/index.html
ADD ./{{ nginx_conf }} /etc/nginx/conf.d/default.conf

RUN /usr/sbin/nginx -t

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
