name: Validators

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ansible-lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: ansible

      - name: terraform-validate
        uses: dflook/terraform-validate@v1.4.1
        with:
          path: terraform-ec2
